name = "SQLDB Postgres"
language = "rust"
type = "provider"
version = "0.10.0"
wit = "../../../crates/provider-sqldb-postgres/wit"

[rust]
target_path = "../../../target"

[provider]
bin_name = "sqldb-postgres-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wasmcloud:postgres"
source = "https://github.com/wasmCloud/wasmCloud/releases/download/wit-wasmcloud-postgres-v0.1.1-draft/wit-wasmcloud-postgres-0.1.1-draft.tar.gz"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
