[package]
name = "wasmcloud-provider-kvredis"
version = "0.21.2"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
redis = { workspace = true, features = [
    "tokio-comp",
    "aio",
    "connection-manager",
    "rustls",
] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
wasmcloud-provider-wit-bindgen = { workspace = true, features = [ "otel" ] }

[dev-dependencies]
async-nats = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = [ "v4", "fast-rng" ] }
wasmcloud-control-interface = { workspace = true }
wasmcloud-test-util = { workspace = true }
