[package]
name = "wasmcloud-actor"
version = "0.1.0"
description = "wasmCloud actor library giving access to interfaces provided by wasmCloud host runtime"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = [
    "component",
    "futures",
    "rand",
    "tokio",
    "uuid",
]

component = [
    "wit-bindgen",
]

[dependencies]
futures = { workspace = true, optional = true, features = ["std"] }
rand = { workspace = true, optional = true }
rmp-serde = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] } # TODO: Make optional once `wasi-http` integrated
serde_bytes = { workspace = true, features = ["std"] } # TODO: Make optional once `wasi-http` integrated
tokio = { workspace = true, optional = true }
uuid = { workspace = true, features = ["serde"], optional = true }
wasmcloud-actor-macros = { workspace = true, optional = true }
wasmcloud-compat = { workspace = true } # TODO: Make optional once `wasi-http` integrated
wit-bindgen = { workspace = true, features = ["macros"], optional = true }
