name: Release

on:
  push:
    branches:
      - feature/*
jobs:
  package:
    runs-on: ubuntu-latest
    env:
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Cross
        run: cargo install cross
      - name: Compile amd64
        run: cross build --target x86_64-unknown-linux-gnu --release
      - name: Compile arm64
        run: cross build --target armv7-unknown-linux-gnueabihf --release
      - name: Install NFPM
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh
      - name: Package amd64 (Debian)
        run: ./bin/nfpm pkg --packager deb -f build/nfpm.amd64.yaml
      - name: Package arm64 (Debian)
        run: ./bin/nfpm pkg --packager deb -f build/nfpm.arm64.yaml
      - name: Package amd64 (RPM)
        run: ./bin/nfpm pkg --packager rpm -f build/nfpm.amd64.yaml
      - name: Package arm64 (RPM)
        run: ./bin/nfpm pkg --packager rpm -f build/nfpm.arm64.yaml
      - name: Push amd64 (Debian)
        run: curl -F "package[distro_version_id]=190" -F "package[package_file]=@$(ls wash_*_amd64.deb)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/wascc/packages.json
      - name: Push arm64 (Debian)
        run: curl -F "package[distro_version_id]=190" -F "package[package_file]=@$(ls wash_*_arm64.deb)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/wascc/packages.json
      - name: Push x86_64 (RPM)
        run: curl -F "package[distro_version_id]=204" -F "package[package_file]=@$(ls wash-*.x86_64.rpm)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/wascc/packages.json
      - name: Push aarch64 (RPM)
        run: curl -F "package[distro_version_id]=204" -F "package[package_file]=@$(ls wash-*.aarch64.rpm)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/wascc/packages.json
