[package]
name = "wasmcloud-host"
version = "0.18.1"
authors = ["wasmCloud Team"]
edition = "2018"
homepage = "https://wasmcloud.dev"
repository = "https://github.com/wasmCloud/wasmCloud"
description = "A secure, distributed, WebAssembly actor model runtime for the cloud, edge, and everything in between"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-host"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasmcloud", "wapc", "actors"]
categories = ["wasm", "api-bindings"]

[features]
default = ["wasm3"]
wasmtime = ["wasmtime-provider"]
wasm3 = ["wasm3-provider"]

[dependencies]
actix = "0.11"
actix-rt = "2.1.0"
chrono = "0.4.19"
crossbeam-channel = "0.5.0"
data-encoding = "2.3.1"
envmnt = "0.9"
futures = "0.3"
lazy_static = "1.4.0"
libloading = "0.7.0"
log = "0.4.11"
nats = "0.8.6"
oci-distribution = "0.6"
once_cell = "1.5.2"
parking_lot = "0.11.1"
provider-archive ="0.4.0"
rand = "0.8.3"
ring = "0.16.19"
rmp-serde = "0.15.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8.14"
uuid = {version = "0.8", features  = ["serde", "v4"]}
wapc = "0.10.1"
wascap = "0.6.0"
serde_bytes = "0.11.5"
wasmcloud-actor-keyvalue = "0.2.0"
wasmcloud-control-interface = { path = "../wasmcloud-control-interface", version = "0.3.1" }

wasm3-provider = { version = "0.0.2", optional = true}
wasmtime-provider = { version = "0.0.3" , optional = true}

[dependencies.wasmcloud-provider-core]
#path = "../wasmcloud-provider-core"
version="0.1.0"

[dependencies.wasmcloud-nats-kvcache]
#path = "../../../capability-providers/nats-kvcache"
version = "0.5.1"
features=["static_plugin"]

[dev-dependencies]
provider-archive = "0.4.0"
reqwest = "0.11"
