name = "HTTP Client"
language = "rust"
version = "0.12.0"
type = "provider"
wit = "../../../crates/provider-http-client/wit"

[rust]
target_dir = "../../../"

[provider]
bin_name = "http-client-provider"
vendor = "wasmCloud"
