version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    all-cargo:
      patterns:
      - "*"
- package-ecosystem: "cargo"
  directory: "/tests/components/rust"
  schedule:
    interval: "monthly"
  groups:
    all-cargo-tests:
      patterns:
      - "*"
- package-ecosystem: "cargo"
  directory: "/examples/rust/components/http-hello-world"
  schedule:
    interval: "monthly"
  groups:
    all-cargo-examples-hello:
      patterns:
      - "*"
- package-ecosystem: "cargo"
  directory: "/examples/rust/components/http-keyvalue-counter"
  schedule:
    interval: "monthly"
  groups:
    all-cargo-examples-counter:
      patterns:
      - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    all-github-actions:
      patterns:
      - "*"
- package-ecosystem: "github-actions"
  directory: "/.github/actions/build-nix"
  schedule:
    interval: "monthly"
  groups:
    all-github-actions-build-nix:
      patterns:
      - "*"
- package-ecosystem: "github-actions"
  directory: "/.github/actions/install-nix"
  schedule:
    interval: "monthly"
  groups:
    all-github-actions-install-nix:
      patterns:
      - "*"
- package-ecosystem: "docker"
  directories:
    - "**/*Dockerfile*"
  schedule:
    interval: "monthly"
  groups:
    all-docker:
      patterns:
      - "*"
