name = "HTTP Server"
language = "rust"
version = "0.26.1"
type = "provider"

[rust]
target_dir = "../../../target"

[provider]
bin_name = "http-server-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
