[package]
name = "wasmcloud-runtime"
version = "0.3.0"
description = "wasmCloud runtime library"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[features]
log = [
    "tracing/log"
]

[dependencies]
anyhow = { workspace = true, features = ["std"] }
async-nats = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true, features = ["async-await", "std"] }
http = { workspace = true }
hyper = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
nkeys = { workspace = true }
rand = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["io-util", "rt-multi-thread", "sync"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
wasm-tokio = { workspace = true }
wascap = { workspace = true }
wasmcloud-component-adapters = { workspace = true }
wasmcloud-core = { workspace = true }
wasmparser = { workspace = true }
wasmtime = { workspace = true, features = ["addr2line", "async", "cache", "component-model", "coredump", "cranelift", "parallel-compilation", "pooling-allocator" ] }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
wit-component = { workspace = true }
wit-parser = { workspace = true }
wrpc-runtime-wasmtime = { workspace = true }
wrpc-transport = { workspace = true }
wrpc-transport-legacy = { workspace = true }
wrpc-transport-nats = { workspace = true }
wrpc-types = { workspace = true }

[dev-dependencies]
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
test-components = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-std", "macros", "net"] }
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter", "fmt", "json", "std"] }
wasmcloud-component = { workspace = true, features = ["uuid"] }
