name = "KV Nats"
language = "rust"
type = "provider"
version = "0.4.1"
wit = "../../../crates/provider-keyvalue-nats/wit"

[rust]
target_path = "../../../target"

[provider]
bin_name = "keyvalue-nats-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wrpc:keyvalue"
source = "file://../../../wit/keyvalue/wit"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
