name = "Messaging Kafka"
language = "rust"
type = "provider"
version = "0.6.1"
wit = "../../../crates/provider-messaging-kafka/wit"

[rust]
target_dir = "../../"

[provider]
bin_name = "messaging-kafka-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wasmcloud:messaging"
source = "file://../../../wit/messaging/wit"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
