[package]
name = "wasmcloud-provider-lattice-controller"
version = "0.3.3"
edition = "2021"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
chrono = "0.4"
crossbeam="0.8"
futures = "0.3"
log = "0.4"
once_cell = "1.8"
reqwest = "0.11"
rmp-serde = "0.15"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
wascap = "0.8.0"
wasmbus-rpc = "0.7.1"
wasmcloud-control-interface = "0.11"

# test dependencies
[dev-dependencies]
wasmcloud-test-util = "0.2"

[[bin]]
name = "lattice-controller"
path = "src/main.rs"
