name = "wadm"
language = "rust"
type = "provider"
version = "0.1.0"
wit = "../../../crates/provider-wadm/wit"

[rust]
target_path = "../../../target"

[provider]
bin_name = "wadm-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wasmcloud:wadm"
source = "https://github.com/wasmCloud/wadm/releases/download/wit-wasmcloud-wadm-v0.2.0/wit-wasmcloud-wadm-0.2.0.tar.gz"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
