# codegen.toml

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@8310dedc8614720c9cd4ac3069603f8c6ee73adc/blobstore/blobstore.smithy"

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/core"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]

[rust]
output_dir = "gen"

[[rust.files]]
path = "blobstore.rs"
namespace = "org.wasmcloud.interface.blobstore"



