name = "Blobstore Azure"
language = "rust"
type = "provider"
version = "0.6.1"
wit = "../../../crates/provider-blobstore-azure/wit"

[rust]
target_path = "../../../target"

[provider]
bin_name = "blobstore-azure-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wrpc:blobstore"
source = "https://github.com/wrpc/blobstore/archive/refs/tags/v0.2.0.tar.gz"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
