[package]
name = "blobby"
version = "0.5.1"
authors = ["wasmCloud Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "blobby"

[workspace]

[dependencies]
http = "1.1.0"
wasmcloud-component = "0.2.0"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
