[package]
name = "wit-bindgen-wasmcloud-provider"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = """
Bindgen macro for binary-based wasmCloud capability providers written in Rust
"""

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }
heck = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
# This version of syn is required due to current version of wasmtime_component_macro that
# has been vendored in this crate. It can be upgraded when the macros themselves update
# (see: src/vendor/wasmtime_component_macro.rs)
syn = { version = "1", features = [ "parsing", "full", "visit-mut", "extra-traits" ] }
wasmtime-wit-bindgen = { workspace = true }
wit-parser = { workspace = true }
