name = "Blobstore FS"
language = "rust"
type = "provider"
version = "0.11.1"
wit = "../../../crates/provider-blobstore-fs/wit"

[rust]
target_dir = "../../"

[provider]
bin_name = "blobstore-fs-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wrpc:blobstore"
source = "https://github.com/wrpc/blobstore/archive/refs/tags/v0.2.0.tar.gz"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
