[package]
name = "check-uri"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = { version = "0.7", features=["runtime"] }
tokio = { version="1", features=["full"] }
