# codegen.toml

[[models]]
path = "."
files = [ "wasmcloud-model.smithy", "wasmcloud-core.smithy" ]

[rust]
output_dir = "."

#[[rust.files]]
#path = "../src/wasmbus_core.rs"
#namespace = "org.wasmcloud.core"
#crate = "wasmbus_core"

[[rust.files]]
path = "../../../codegen/src/wasmbus_model.rs"
namespace = "org.wasmcloud.model"
crate = "wasmbus_rpc_model"

