[package]
name = "wasmcloud-provider-httpserver"
version = "0.18.3"
description = "Http server for wasmcloud, using warp. This package provides a library, and a capability provider with the 'wasmcloud:httpserver' contract."

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
flume = { workspace = true, features = ["async"] }
futures = { workspace = true }
http = { workspace = true }
serde_bytes = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true, features = ["parse"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
warp = { workspace = true, features = ["tls"] }
wasmbus-rpc = { workspace = true, features = ["otel"] }

[lib]
name = "wasmcloud_provider_httpserver"
path = "src/lib.rs"

[[bin]]
name = "httpserver"
path = "bin/httpserver.rs"
