[package]
name = "wasmcloud-provider-blobstore-s3"
version = "0.11.1"
description = """
S3-compatible object store capability provider for wasmcloud, satisfying the 'wasmcloud:blobstore' capability contract.
"""

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true, features = ["rustls", "rt-tokio"] }
aws-smithy-runtime = { workspace = true, features = ["client", "tls-rustls"] }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hyper-rustls = { version = "0.25", features = [
    "http2",
    "ring",
    "webpki-tokio",
], default-features = false } # Downgrade for `aws-smithy-runtime` compatibility
rustls = { version = "0.23", default-features = false } # Downgrade for `aws-smithy-runtime` compatibility
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
tracing = { workspace = true }
wasmcloud-provider-sdk = { workspace = true, features = ["otel"] }
wrpc-interface-blobstore = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
wasmcloud-test-util = { workspace = true, features = ["testcontainers"] }
