[package]
name = "wasmbus-rpc"
version = "0.7.4"
authors = [ "wasmcloud Team" ]
license = "Apache-2.0"
description = "Runtime library for actors and capability providers"
homepage = "https://github.com/wasmcloud/weld"
repository = "https://github.com/wasmcloud/weld"
documentation = "https://docs.rs/wasmbus-rpc"
readme = "README.md"
edition = "2021"

# don't push build.rs
exclude = [ "build.rs" ]

[features]
# Warning: Don't change serialization - things will break
default = [ ]
BigInteger = [ "num-bigint" ]
BigDecimal = [ "bigdecimal" ]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
cfg-if = "1.0"
log = "0.4"
minicbor = { version = "0.13", features = ["std", "partial-skip-support" ] }
nkeys = "0.2"
rmp-serde = { version = "0.15.4" }
serde_bytes = "0.11"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
time = "0.3.7"
tokio-timer = "0.2"
toml = "0.5"
wasmbus-macros = { path = "../macros", version = "0.1.7" }

#BigInteger support
num-bigint = { version = "0.4", optional = true }
#BigDecimal support
bigdecimal = { version = "0.3", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"]}
futures = "0.3"
nats-aflowt = "0.16.104"
once_cell = "1.8"
crossbeam = "0.8"
uuid = { version = "0.8", features=["v4", "serde"] }
wascap = "0.8.0"
ring = "0.16"
pin-utils = "0.1"
data-encoding = "2.3"

[dev-dependencies]
regex = "1"
env_logger = "0.9.0"

[build-dependencies]
weld-codegen = "0.3.3"
