[package]
name = "wasmcloud-test-util"
version = "0.19.0"
rust-version = "1.78"
description = """
Utilities for testing wasmCloud hosts, providers, and components.
"""

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[features]
http = ["dep:reqwest"]
os = []
testcontainers = ["dep:testcontainers"]

[dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
nkeys = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
testcontainers = { workspace = true, optional = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
wascap = { workspace = true }
wasmcloud-control-interface = { workspace = true }
wasmcloud-core = { workspace = true }
wasmcloud-host = { workspace = true }
wasmcloud-secrets-types = { workspace = true }
reqwest = { workspace = true, features = [ "json", "rustls-tls"], optional = true }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tempfile = { workspace = true }


[target.'cfg(unix)'.dependencies]
testcontainers = { workspace = true, optional = true, features = ["watchdog"] }
