[package]
name = "http-task-manager"
edition = "2021"
version = "0.1.0"
description = """
A task manager exposed via HTTP API and wRPC, with Postgres as a backend 
"""

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true, features = [ "std" ] }
bytes = { workspace = true, features = [ "default", "serde" ] }
chrono = { workspace = true }
include_dir = {workspace = true, features = [ "glob" ] }
serde = { workspace = true, features = [ "std", "derive", "alloc" ] }
serde_json = { workspace = true, features = [ "std" ] }
wit-bindgen = { workspace = true, features = [ "default" ] }

[dev-dependencies]
merkle_hash = { workspace = true, features = [ "encode" ] }
reqwest = { workspace = true, features = ["rustls-tls", "json"] }
serde = { workspace = true, features = [ "std", "derive", "alloc" ] }
testcontainers-modules = { workspace = true, features = ["postgres"]  }
tokio = { workspace = true, features = [ "macros", "rt-multi-thread", "process", "io-std", "io-util"] }

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
bytes = { version = "1", default-features = false }
chrono = { version = "0.4", default-features = false }
include_dir = { version = "0.7.4", default-features = false}
merkle_hash = { version = "3.7.0", default-features = false }
reqwest = { version = "0.12", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
testcontainers-modules = { version = "0.9.0", default-features = false }
tokio = { version = "1", default-features = false }
wit-bindgen = { version = "0.32", default-features = false }
