[package]
name = "wasmcloud-host"
version = "0.1.0"
description = "wasmCloud host runtime library"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[features]
log = [
    "tracing/log"
]

[dependencies]
anyhow = { workspace = true, features = ["std"] }
async-trait = { workspace = true }
futures = { workspace = true, features = ["std"] }
log = { workspace = true }
rand = { workspace = true, features = ["std"] }
rmp-serde = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
wascap = { workspace = true }
wasmcloud-interface-logging = { workspace = true }
wasmcloud-interface-numbergen = { workspace = true }
wasmparser = { workspace = true }
wasmtime = { workspace = true, features = ["async", "cache", "component-model", "cranelift", "jitdump", "parallel-compilation", "pooling-allocator", "vtune"] }
wasmtime-wasi = { workspace = true, features = ["sync", "preview2"] }
