[package]
name = "wasmcloud-host"
version = "0.80.0"
description = "wasmCloud host library"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
async-nats = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
cloudevents-sdk = { workspace = true }
futures = { workspace = true, features = ["async-await", "std"] }
hex = { workspace = true, features = ["std"] }
http = { workspace = true }
humantime = { workspace = true }
oci-distribution = { workspace = true, features = ["rustls-tls"] }
names = { workspace = true }
nkeys = { workspace = true }
opentelemetry-nats = { workspace = true }
provider-archive = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls"] }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tokio = { workspace = true, features = ["fs", "io-std", "io-util", "process", "rt-multi-thread", "time"] }
tokio-stream = { workspace = true, features = ["net", "time"] }
tracing = { workspace = true }
ulid = { workspace = true, features = ["std"] }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
wascap = { workspace = true }
wasmcloud-compat = { workspace = true }
wasmcloud-control-interface = { workspace = true }
wasmcloud-core = { workspace = true, features = ["otel"] }
wasmcloud-runtime = { workspace = true }
wasmcloud-tracing = { workspace = true, features = ["otel"] }
