[package]
name = "wasmcloud-auth-natsaccount"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
description = "Authorizer plugin for wasmCloud that consults a NATS account server"

[dependencies]
reqwest =  {version = "0.11.3", features = ["blocking"] }
wasmcloud-host = { path = "../wasmcloud-host"}
wascap = "0.6.0"
url = "2.2.1"
serde_json = "1.0.64"