[package]
name = "wasmcloud-provider-custom-template"
version = "0.1.0"
edition = "2021"
description = """
A capability provider template built for implementation of custom capabilities.
"""

[workspace]

[badges.maintenance]
status = "actively-developed"

[dependencies]
anyhow = "1.0.82"
async-nats = "0.33.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1"
wasmcloud-provider-sdk = { version = "0.11.0", features = ["otel"] }
wit-bindgen-wrpc = "0.8"
