[package]
name = "bencher"
version = "0.1.0"
authors = ["wasmcloud team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmcloud-host = { path = "../../crates/wasmcloud-host", version="0.15.4" }
actix-rt = "2.1.0"
wasmcloud-actor-core = "0.2.0"
wasmcloud-actor-http-server = "0.1.0"
serde = { version = "1.0.123", features = ["derive"]}
serde_json = "1.0.62"