[package]
name = "dog-fetcher"
edition = "2021"
version = "0.1.1"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasi = { version = "0.14.7", features = ["std"] }
wit-bindgen = "0.43"
