[package]
name = "wasmcloud-provider-httpserver"
version = "0.15.1"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
atty = "0.2"
base64 = "0.13"
bytes = "1.0"
futures = "0.3"
http = "0.2"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
warp = { version="0.3", features=["tls"] }
wasmcloud-interface-httpserver = "0.5.0"
wasmbus-rpc = "0.8.5"

[dev-dependencies]
assert_matches = "1.5"
blake2 = "0.9"
reqwest = { version = "0.11", features = ["json"]}
wasmcloud-test-util = "0.3.1"

[lib]
name = "wasmcloud_provider_httpserver"
path = "src/lib.rs"

[[bin]]
name = "httpserver"
path = "bin/main.rs"

