name = "sqldb-postgres-query"
version = "0.1.0"
language = "tinygo"
type = "component"

[component]
wit_world = "component"
wasm_target = "wasm32-wasi"
destination = "build/sqldb_postgres_query_s.wasm"
