[package]
name = "wasmcloud-tracing"
version = "0.11.0"
description = "wasmCloud tracing functionality"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
otel = [
    "opentelemetry",
    "opentelemetry_sdk",
    "opentelemetry-appender-tracing",
    "tracing-opentelemetry",
    "opentelemetry-otlp",
    "wasmcloud-core/otel",
    "wasmcloud-core/rustls-native-certs",
]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
heck = { workspace = true }
once_cell = { workspace = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true, features = [
    "logs",
    "metrics",
    "trace",
    "rt-tokio",
] }
opentelemetry-appender-tracing = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, features = [
    "grpc-tonic",
    "http-proto",
    "logs",
    "trace",
    "metrics",
    "reqwest-client",
], optional = true }
reqwest-0_11 = { workspace = true, features = ["rustls-tls"] }
tracing = { workspace = true, features = ["log"] }
tracing-appender = { workspace = true }
tracing-flame = { workspace = true }
tracing-opentelemetry = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = [
    "ansi",
    "env-filter",
    "fmt",
    "json",
] }
http = { workspace = true }
wasmcloud-core = { workspace = true }
