name: Benchmark Chart

env:
  HELM_VERSION: v3.16.3
  CHART_TESTING_NAMESPACE: chart-testing

on:
  push:
    tags:
      - 'benchmark-chart-v[0-9].[0-9]+.[0-9]+'
  pull_request:
    branches: [main]
    paths:
      - 'charts/benchmark/**'
      - '.github/workflows/benchmark-chart.yml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      # Shallow fetch the latest main so the chart-testing action can compare
      - name: Shallow fetch main
        run: git fetch origin main --depth=1

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: ${{ env.HELM_VERSION }}

      # Used by helm chart-testing below
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12.2'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
        with:
          version: v3.12.0
          yamllint_version: 1.35.1
          yamale_version: 5.0.0

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          version: "v0.22.0"

      - name: Run chart-testing lint and install
        # We are only testing that everything installs and the k6 tests start. The k6 tests will just get
        # errors because the endpoint doesn't exist, which is fine for making sure everything deploys. We
        # can come back and do a full app deploy with wasmCloud and check results later.
        #
        # A couple of notes about the other flags here:
        # - The fullnameOverride is needed because the generated test name makes the service name too long in the k6-operator
        # - The fullnameOverride isn't in the values schema for the k6-operator, so we need to skip schema validation
        run: |
          ct lint-and-install --config charts/benchmark/ct.yaml --helm-extra-set-args='--set=test.url=http://fake-url:8000,k6-operator.fullnameOverride=test --skip-schema-validation'

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/benchmark-chart-v') }}
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Package
        run: |
          helm package charts/benchmark --dependency-update -d .helm-charts

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the organization name for ghcr.io
        run: |
          echo "GHCR_REPO_NAMESPACE=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Publish
        run: |
          for chart in .helm-charts/*; do
            if [ -z "${chart:-}" ]; then
              break
            fi
            helm push "${chart}" "oci://ghcr.io/${{ env.GHCR_REPO_NAMESPACE }}/charts"
          done
