name: CODEGEN

on:
  push:
    branches: [main]
    paths:
      - "codegen/**"
    tags:
      - "weld-codegen-v*"
  pull_request:
    branches: [main]
    paths:
      - "codegen/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./codegen

jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: run_all_tests_clippy_fmt
        run: |
          cd ${{ env.working-directory }}
          make test
          make rust-check

  github_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: rust_test
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

  crates_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: crates-release-action
        uses: wasmcloud/common-actions/crates-release@main
        with:
          working-directory: ${{ env.working-directory }}
          crates-token: ${{ secrets.CRATES_PUBLISH_TOKEN }}
