name: Build Gitpod Docker Artifact
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.gitpod.Dockerfile'
        
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Determine Short SHA
        run: echo ${{ github.sha }} | tail -c 8 | (read; echo SHORT_SHA=$REPLY) >> $GITHUB_ENV
      -
        name: Sanitize Repo Name for Tagging
        run: echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | (read; echo REPO_LOWER=$REPLY) >> $GITHUB_ENV
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURECR_PUSH_URL }}
          username: ${{ secrets.AZURECR_PUSH_USER }}
          password: ${{ secrets.AZURECR_PUSH_PASSWORD }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: '.gitpod.Dockerfile'
          push: true
          tags: |
            wasmcloud.azurecr.io/${{ env.REPO_LOWER }}_gitpod:latest
            wasmcloud.azurecr.io/${{ env.REPO_LOWER }}_gitpod:${{ env.SHORT_SHA }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
