name: Go

on:
  push:
    branches:
      - main
    paths:
      - "go/*"
  pull_request:
    branches:
      - main
    paths:
      - "go/*"

jobs:
  vanity-urls:
    runs-on: node16
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        working-directory: go
        run: npx wrangler@2 pages deployment create --branch=main --project-name=wasmcloud-go-modules vanity-urls
