name: helm-charts

on:
  push:
    tags:
      - 'wasmcloud-host-chart-v[0-9].[0-9]+.[0-9]+'
      - 'wasmcloud-platform-chart-v[0-9].[0-9]+.[0-9]+'
      - 'benchmark-chart-v[0-9].[0-9]+.[0-9]+'
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-charts.yml'

permissions:
  contents: read

env:
  HELM_VERSION: v3.16.3
  CHART_TESTING_NAMESPACE: chart-testing

jobs:
  # Determine which charts have changed
  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      wasmcloud-host: ${{ steps.changes.outputs.wasmcloud-host }}
      wasmcloud-platform: ${{ steps.changes.outputs.wasmcloud-platform }}
      benchmark: ${{ steps.changes.outputs.benchmark }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            wasmcloud-host:
              - 'charts/wasmcloud-host/**'
              - '.github/workflows/helm-charts.yml'
            wasmcloud-platform:
              - 'charts/wasmcloud-platform/**'
              - '.github/workflows/helm-charts.yml'
            benchmark:
              - 'charts/benchmark/**'
              - '.github/workflows/helm-charts.yml'

  # Validate wasmcloud-host chart
  validate-wasmcloud-host:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.wasmcloud-host == 'true' || startsWith(github.ref, 'refs/tags/wasmcloud-host-chart-v') }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Shallow fetch main
        run: git fetch origin main --depth=1

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12.2'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          version: v3.12.0
          yamllint_version: 1.35.1
          yamale_version: 5.0.0

      - name: Run chart-testing (lint)
        run: ct lint --config charts/wasmcloud-host/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          version: 'v0.26.0'

      - name: Install nats in the test cluster
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo update
          helm install nats nats/nats -f charts/ci/nats-values.yaml --namespace ${{ env.CHART_TESTING_NAMESPACE }} --create-namespace

      - name: Run chart-testing install (same namespace)
        run: ct install --config charts/wasmcloud-host/ct.yaml --namespace ${{ env.CHART_TESTING_NAMESPACE }}

      - name: Run chart-testing install (across namespaces)
        run: ct install --config charts/wasmcloud-host/ct.yaml --helm-extra-set-args "--set=config.natsAddress=nats://nats-headless.${{ env.CHART_TESTING_NAMESPACE }}.svc.cluster.local"

  # Validate wasmcloud-platform chart
  validate-wasmcloud-platform:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.wasmcloud-platform == 'true' || startsWith(github.ref, 'refs/tags/wasmcloud-platform-chart-v') }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Shallow fetch main
        run: git fetch origin main --depth=1

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12.2'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          version: v3.12.0
          yamllint_version: 1.35.1
          yamale_version: 5.0.0

      - name: Run chart-testing (lint)
        run: ct lint --config charts/wasmcloud-platform/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          version: 'v0.26.0'

      - name: Run chart-testing (install)
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo update
          kubectl create ns ${{ env.CHART_TESTING_NAMESPACE }}
          ct install --config charts/wasmcloud-platform/ct.yaml --namespace ${{ env.CHART_TESTING_NAMESPACE }} --helm-extra-set-args "--set=wadm.wadm.config.nats.server=nats://nats-headless.${{ env.CHART_TESTING_NAMESPACE }}.svc.cluster.local"

  # Validate benchmark chart
  validate-benchmark:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.benchmark == 'true' || startsWith(github.ref, 'refs/tags/benchmark-chart-v') }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Shallow fetch main
        run: git fetch origin main --depth=1

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12.2'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          version: v3.12.0
          yamllint_version: 1.35.1
          yamale_version: 5.0.0

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          version: 'v0.26.0'

      - name: Run chart-testing lint and install
        run: |
          ct lint-and-install --config charts/benchmark/ct.yaml --helm-extra-set-args='--set=test.url=http://fake-url:8000,k6-operator.fullnameOverride=test --skip-schema-validation'

  # Publish charts
  publish:
    runs-on: ubuntu-24.04
    # Run on tags, but only if validation jobs didn't fail (skipped is OK)
    if: |
      always() &&
      startsWith(github.ref, 'refs/tags/') &&
      !contains(needs.*.result, 'failure')
    needs:
      - validate-wasmcloud-host
      - validate-wasmcloud-platform
      - validate-benchmark
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Determine chart to publish
        id: chart
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          if [[ "$tag" == wasmcloud-host-chart-v* ]]; then
            echo "name=wasmcloud-host" >> "$GITHUB_OUTPUT"
            echo "dir=charts/wasmcloud-host" >> "$GITHUB_OUTPUT"
          elif [[ "$tag" == wasmcloud-platform-chart-v* ]]; then
            echo "name=wasmcloud-platform" >> "$GITHUB_OUTPUT"
            echo "dir=charts/wasmcloud-platform" >> "$GITHUB_OUTPUT"
            echo "has_deps=true" >> "$GITHUB_OUTPUT"
          elif [[ "$tag" == benchmark-chart-v* ]]; then
            echo "name=benchmark" >> "$GITHUB_OUTPUT"
            echo "dir=charts/benchmark" >> "$GITHUB_OUTPUT"
            echo "has_deps=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Add Helm repos for dependencies
        if: ${{ steps.chart.outputs.has_deps == 'true' }}
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo update

      - name: Build dependencies
        if: ${{ steps.chart.outputs.has_deps == 'true' }}
        working-directory: ${{ steps.chart.outputs.dir }}
        run: helm dependency build

      - name: Package chart
        run: helm package ${{ steps.chart.outputs.dir }} -d .helm-charts

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the organization name
        run: echo "GHCR_REPO_NAMESPACE=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Publish chart
        run: |
          for chart in .helm-charts/*; do
            if [ -z "${chart:-}" ]; then
              break
            fi
            helm push "${chart}" "oci://ghcr.io/${{ env.GHCR_REPO_NAMESPACE }}/charts"
          done
