name: LATTICE-CONTROLLER

on:
  push:
    branches: [ main ]
    paths:
    - "lattice-controller/**"
    tags:
    - 'lattice-controller-v*'
  pull_request:
    branches: [ main ]
    paths:
    - "lattice-controller/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./lattice-controller
  WASH_ISSUER_KEY: ${{ secrets.WASMCLOUD_ACCOUNT_OFFICIAL }}
  WASH_SUBJECT_KEY: ${{ secrets.WASMCLOUD_LATTICECONTROLLER }}

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # If your integration tests require nats or redis, run them here
    - id: run-nats
      uses: wasmcloud/common-actions/run-nats@main
    - id: rust-check-action
      uses: wasmcloud/common-actions/rust-check@main
      with:
        working-directory: ${{ env.working-directory }}

  build_artifact:
    needs: rust_check
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wasmcloud/common-actions/install-wash@main
      - uses: wasmcloud/common-actions/install-cross@main

      - name: Build full provider archive
        run: make par-full
        working-directory: ${{ env.working-directory }}
      
      - name: Upload provider archive to GH Actions
        uses: actions/upload-artifact@v2
        with:
          name: provider-archive
          path: ${{ env.working-directory }}/build/*.par.gz

  github_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: build_artifact
    runs-on: ubuntu-latest
    steps:
    - name: Download provider archive
      uses: actions/download-artifact@v2
      with:
        name: provider-archive
        path: ${{ env.working-directory }}/build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.working-directory }}/build/*.par.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        draft: false

  artifact_release:
    needs: build_artifact
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download provider archive
        uses: actions/download-artifact@v2
        with:
          name: provider-archive
          path: ${{ env.working-directory }}/build

      - name: Determine artifact metadata
        run: |
          echo "oci-repository=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].name' | sed 's/wasmcloud-provider-//')" >> $GITHUB_ENV
          echo "oci-version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].version')" >> $GITHUB_ENV
        working-directory: ${{ env.working-directory }}

      - name: Push provider archive to AzureCR
        uses: wasmcloud/common-actions/oci-artifact-release@main
        with:
          artifact-path: ${{ env.working-directory }}/build/${{ env.oci-repository }}.par.gz
          oci-url: ${{ secrets.AZURECR_PUSH_URL }}
          oci-repository: ${{ env.oci-repository }}
          oci-version: ${{ env.oci-version }}
          oci-username: ${{ secrets.AZURECR_PUSH_USER }}
          oci-password: ${{ secrets.AZURECR_PUSH_PASSWORD }}
