name: lint-conventional-commits

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: taiki-e/cache-cargo-install-action@v2
      #   with:
      #     tool: convco

      # - name: Check conventional commits formatting
      #   id: cc-lint
      #   continue-on-error: true
      #   shell: bash
      #   run: |
      #     convco check '${{ github.event.pull_request.base.sha }}'..'${{ github.event.pull_request.head.sha }}'

      - name: Install commitsar
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4
        with:
          repo: aevea/commitsar
          tag: v0.20.2
          cache: enable

      - name: Check commits
        id: cc-lint
        continue-on-error: true
        run: |
          commitsar -v -s=false

      # Save the failing pr number for the commenting action to later use
      - name: Save PR metadata
        run: |
          mkdir -p meta
          echo ${{ github.event.number }} > meta/failing-pr-num
          echo ${{ steps.cc-lint.outcome }} > meta/outcome
      - uses: actions/upload-artifact@v4
        with:
          name: meta
          path: meta/*

      - name: Propagate lint failure
        if: ${{ steps.cc-lint.outcome != 'success' }}
        run: |
          exit -1
