name: Release - amd64

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  package:
    runs-on: ubuntu-20.04
    env:
      REF: ${{ github.ref }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile wash
        run: cargo build --release
      - name: Install NFPM
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh
      - name: Package amd64 (Debian)
        run: |
          export VERSION=$(echo $REF | cut -d/ -f3)
          ./bin/nfpm pkg --packager deb -f build/nfpm.amd64.yaml
          ./bin/nfpm pkg --packager rpm -f build/nfpm.amd64.yaml
      - name: Push amd64 (Ubuntu 19.04)
        run: curl -F "package[distro_version_id]=203" -F "package[package_file]=@$(ls wash_*_amd64.deb)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/core/packages.json
      - name: Push amd64 (Ubuntu 20.04)
        run: curl -F "package[distro_version_id]=210" -F "package[package_file]=@$(ls wash_*_amd64.deb)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/core/packages.json
      - name: Push x86_64 (Fedora 32)
        run: curl -F "package[distro_version_id]=216" -F "package[package_file]=@$(ls wash-*.x86_64.rpm)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/core/packages.json
