name: Release - amd64

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  package:
    runs-on: ubuntu-UBUNTU
    env:
      REF: ${{ github.ref }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile wasmcloud
        run: cargo build --release
      - name: Install NFPM
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh
      - name: Package amd64 (deb & rpm)
        run: |
          export VERSION=$(echo $REF | cut -d/ -f3)
          ./bin/nfpm pkg --packager deb -f build/nfpm.amd64.yaml
          ./bin/nfpm pkg --packager rpm -f build/nfpm.amd64.yaml
      - name: Push amd64 (deb)
        run: |
          debs=(35 150 155 156 190 203 206 207 210 215 219)
          for distro_version in "${debs[@]}"; do
            curl -F "package[distro_version_id]=${distro_version}" -F "package[package_file]=@$(ls wasmcloud_*_amd64.deb)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/core/packages.json;
          done
      - name: Push x86_64 (rpm)
        run: |
          rpms=(140 141 146 194 204 205 209 216)
          for distro_version in "${rpms[@]}"; do 
            curl -F "package[distro_version_id]=${distro_version}" -F "package[package_file]=@$(ls wasmcloud-*.x86_64.rpm)" https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/repos/wasmCloud/core/packages.json;
          done

