name: ts-test

on:
  workflow_call: {}

env:
  TURBO_CACHE_DIR: ./.turbo/cache
  TURBO_TELEMETRY_DISABLED: true
  TURBO_RUN_SUMMARY: true

defaults:
  run:
    working-directory: ./typescript

permissions:
  contents: read

jobs:
  test:
    name: test:format-lint-unit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup
        uses: ./.github/actions/ts-setup
        with:
          working-directory: ./typescript

      - name: Run Tests
        run: yarn turbo lint format test:unit

  e2e:
    runs-on: ubuntu-latest

    env:
      # store browsers in the node_modules folder
      PLAYWRIGHT_BROWSERS_PATH: 0

    defaults:
      run:
        working-directory: ./typescript/apps/washboard-ui

    strategy:
      matrix:
        wash:
          - version: 0.32.1
          - version: 0.33.0
          - version: 0.34.1

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup
        uses: ./.github/actions/ts-setup
        with:
          working-directory: ./typescript

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Install `wash` CLI
        uses: taiki-e/install-action@6da51af62171044932d435033daa70a0eb3383ba
        with:
          tool: wash-cli@${{ matrix.wash.version }}

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Test Results
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        if: always()
        with:
          name: playwright-report-${{ matrix.wash.version }}
          retention-days: 30
          path: |
            ./typescript/apps/washboard-ui/playwright-report
            ./typescript/apps/washboard-ui/test-results