name: ts-test

on:
  workflow_call: {}

env:
  TURBO_CACHE_DIR: ./.turbo/cache
  TURBO_TELEMETRY_DISABLED: true
  TURBO_RUN_SUMMARY: true

defaults:
  run:
    working-directory: ./typescript

jobs:
  test:
    name: test:format-lint-unit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Setup
        uses: ./.github/actions/ts-setup
        with:
          working-directory: ./typescript

      - name: Run Tests
        run: yarn turbo lint format test:unit

  e2e:
    runs-on: ubuntu-latest

    env:
      # store browsers in the node_modules folder
      PLAYWRIGHT_BROWSERS_PATH: 0

    defaults:
      run:
        working-directory: ./typescript/apps/washboard-ui

    strategy:
      matrix:
        wash:
          - version: 0.32.1
          - version: 0.33.0
          - version: 0.34.1

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Setup
        uses: ./.github/actions/ts-setup
        with:
          working-directory: ./typescript

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Install `wash` CLI
        uses: taiki-e/install-action@2d57bf37fe9fab88b6ec604bfaa8c76ed00ea64a
        with:
          tool: wash-cli@${{ matrix.wash.version }}

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Test Results
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097
        if: always()
        with:
          name: playwright-report-${{ matrix.wash.version }}
          retention-days: 30
          path: |
            ./typescript/apps/washboard-ui/playwright-report
            ./typescript/apps/washboard-ui/test-results