name: washboard

on:
  push:
    paths:
      - 'washboard-ui/**'
    branches:
      - main
    tags:
      - 'washboard-ui-v*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: washboard-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./washboard-ui
    strategy:
      matrix:
        wash:
          - version: 0.27.0
          - version: 0.28.1
          - version: 0.29.2
            release: true
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version-file: ./washboard-ui/.tool-versions
          cache-dependency-path: ./washboard-ui/yarn.lock

      - name: Setup Yarn
        run: |
          corepack enable
          yarn --version

      - name: Cache turbo build setup
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ./washboard-ui/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Prettier
        run: yarn run turbo:format

      - name: ESLint
        run: yarn run turbo:lint

      - name: Unit Tests
        run: yarn run turbo:test:unit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Install wash
        uses: taiki-e/install-action@3451569d988f3b0b3eaccd1d1b539a75ec96f192
        with:
          tool: wash-cli@${{ matrix.wash.version }}

      - name: E2E Tests
        run: yarn run turbo:test:e2e

      - name: Build
        run: yarn run turbo:build

      - name: Compress
        run: tar -C ./packages/washboard-ui/dist -zcvf washboard.tar.gz .

      - name: Upload Artifact
        if: ${{ matrix.wash.release }}
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029
        with:
          name: washboard
          path: ./washboard-ui/washboard.tar.gz

      - name: Upload Playwright Report
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029
        if: always()
        with:
          name: playwright-report
          retention-days: 30
          path: |
            washboard-ui/packages/washboard-ui/wash-${{ matrix.wash.version }}.playwright-report
            washboard-ui/packages/washboard-ui/wash-${{ matrix.wash.version }}.test-results

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/washboard-ui-v')

    steps:
      - name: Download Asset
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: washboard

      - name: Create Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          draft: false
          prerelease: false
          makeLatest: false
          artifacts: washboard.tar.gz
