name: wasmcloud-platform-chart

on:
  push:
    tags:
      - 'wasmcloud-platform-chart-v[0-9].[0-9]+.[0-9]+'
  pull_request:
    paths:
      - 'charts/wasmcloud-platform/**'
      - '.github/workflows/wasmcloud-platform-chart.yml'

permissions:
  contents: read

env:
  HELM_VERSION: v3.13.3
  CHART_TESTING_NAMESPACE: chart-testing

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
        with:
          version: ${{ env.HELM_VERSION }}

      # Used by helm chart-testing below
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.12.0'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f
        with:
          version: v3.9.0
          yamllint_version: 1.32.0
          yamale_version: 4.0.4

      - name: Run chart-testing (lint)
        run: |
          ct lint --config charts/wasmcloud-platform/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab

      - name: Run chart-testing (install)
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo update
          kubectl create ns ${{ env.CHART_TESTING_NAMESPACE }}
          ct install --config charts/wasmcloud-platform/ct.yaml --namespace ${{ env.CHART_TESTING_NAMESPACE }} --helm-extra-set-args "--set=wadm.wadm.config.nats.server=nats://nats-headless.${{ env.CHART_TESTING_NAMESPACE }}.svc.cluster.local"

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/wasmcloud-platform-chart-v') }}
    runs-on: ubuntu-22.04
    needs: validate
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Package
        env:
          CHART_DIR: charts/wasmcloud-platform
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          cd $CHART_DIR
          helm dependency build
          cd -
          helm package $CHART_DIR -d .helm-charts

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the organization name for ghcr.io
        run: |
          echo "GHCR_REPO_NAMESPACE=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Publish
        run: |
          for chart in .helm-charts/*; do
            if [ -z "${chart:-}" ]; then
              break
            fi
            helm push "${chart}" "oci://ghcr.io/${{ env.GHCR_REPO_NAMESPACE }}/charts"
          done
