name: wit-wasmcloud-postgres-publish

on:
  push:
    tags:
      - 'wit-wasmcloud-postgres-v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          sparse-checkout: |
            wit
            .github
      - name: Extract tag context
        id: ctx
        run: |
          version=${GITHUB_REF_NAME#wit-wasmcloud-postgres-v}
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "tarball=wit-wasmcloud-postgres-${version}.tar.gz" >> "$GITHUB_OUTPUT"
          echo "version is ${version}"
      - uses: ./.github/actions/configure-wkg
        with:
          oci-username: ${{ github.repository_owner }}
          oci-password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        working-directory: wit/postgres
        run: wkg wit build -o package.wasm
      - name: Push version-tagged WebAssembly binary to GHCR
        working-directory: wit/postgres
        run: wkg publish package.wasm
      - name: Package tarball for release
        run: |
          tar -cvzf ${{ steps.ctx.outputs.tarball }} -C wit postgres/wit
      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: ${{ steps.ctx.outputs.tarball }}
          make_latest: 'false'
