apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wasmcloud-host.fullname" . }}
  labels:
    {{- include "wasmcloud-host.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "wasmcloud-host.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wasmcloud-host.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: wasmcloud-host
          command: ["wasmcloud"]
        {{- if or (eq .Values.config.observability.enable true) (eq .Values.config.observability.traces.enable true) (eq .Values.config.observability.metrics.enable true) (eq .Values.config.observability.logs.enable true) }}
          arg:
          {{- if .Values.config.observability.enable }}
            - --enable-observability
          {{- end }}
          {{- if .Values.config.observability.endpoint }}
            - --override-observability-endpoint
            - {{ .Values.config.observability.endpoint }}
          {{- end }}
          {{- if .Values.config.observability.protocol }}
            - --observability-protocol
            - {{ .Values.config.observability.protocol }}
          {{- end }}
          {{- if .Values.config.observability.traces.enable }}
            - --enable-traces
          {{ end }}
          {{- if .Values.config.observability.traces.endpoint }}
            - --override-traces-endpoint
            - {{ .Values.config.observability.traces.endpoint }}
          {{- end }}
          {{- if .Values.config.observability.metrics.enable }}
            - --enable-metrics
          {{ end }}
          {{- if .Values.config.observability.metrics.endpoint }}
            - --override-metrics-endpoint
            - {{ .Values.config.observability.metrics.endpoint }}
          {{- end }}
          {{- if .Values.config.observability.logs.enable }}
            - --enable-logs
          {{ end }}
          {{- if .Values.config.observability.logs.endpoint }}
            - --override-logs-endpoint
            - {{ .Values.config.observability.logs.endpoint }}
          {{- end }}
        {{- end }}
          env:
          {{- if .Values.config.enableStructuredLogging }}
          - name: WASMCLOUD_STRUCTURED_LOGGING_ENABLED
            value: "true"
          {{- end }}
          - name: WASMCLOUD_LOG_LEVEL
            value: {{ .Values.config.logLevel | upper | quote }}
          - name: WASMCLOUD_JS_DOMAIN
            value: {{ .Values.config.jetstreamDomain | quote }}
          - name: WASMCLOUD_LATTICE
            value: {{ .Values.config.lattice | quote }}
          - name: WASMCLOUD_NATS_HOST
            value: "127.0.0.1"
          - name: WASMCLOUD_NATS_PORT
            value: "4222"
          - name: WASMCLOUD_RPC_TIMEOUT_MS
            value: "4000"
          {{- if .Values.config.controlTopicPrefix }}
          - name: WASMCLOUD_CTL_TOPIC_PREFIX
            value: {{ .Values.config.controlTopicPrefix }}
          {{- end }}
          {{- if .Values.config.configServiceEnabled }}
          - name: WASMCLOUD_CONFIG_SERVICE
            value: "true"
          {{- end }}
          {{- if .Values.config.allowLatest }}
          - name: WASMCLOUD_OCI_ALLOW_LATEST
            value: "true"
          {{- end }}
          {{- if .Values.config.allowedInsecure }}
          - name: WASMCLOUD_OCI_ALLOWED_INSECURE
            value: {{ include "wasmcloud-host.allowed-insecure" . }}
          {{- end }}
        {{- if .Values.config.policyService.enable }}
          {{- if .Values.config.policyService.topic }}
          - name: WASMCLOUD_POLICY_TOPIC
            value: {{ .Values.config.policyService.topic | quote }}
          {{- end }}
          {{- if .Values.config.policyService.changesTopic }}
          - name: WASMCLOUD_POLICY_CHANGES_TOPIC
            value: {{ .Values.config.policyService.changesTopic | quote }}
          {{- end }}
          {{- if .Values.config.policyService.timeoutMs }}
          - name: WASMCLOUD_POLICY_TIMEOUT
            value: {{ .Values.config.policyService.timeoutMs | quote }}
          {{- end }}
        {{- end }}
          {{- if .Values.config.secrets_topic_prefix }}
          - name: WASMCLOUD_SECRETS_TOPIC
            value: {{ .Values.config.secrets_topic_prefix | quote }}
          {{- end }}
          {{- if .Values.config.maxLinearMemoryBytes }}
          - name: WASMCLOUD_MAX_LINEAR_MEMORY
            value: {{ .Values.config.maxLinearMemoryBytes | int64 }}
          {{- end }}
        {{- if .Values.config.hostLabels }}
          {{- range $key, $value := .Values.config.hostLabels }}
            {{- if $value }}
          - name: WASMCLOUD_LABEL_{{ $key | lower }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
        {{- end }}
          - name: WASMCLOUD_LABEL_kubernetes
            value: "true"
          - name: WASMCLOUD_LABEL_pod_name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WASMCLOUD_LABEL_node_name
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources.wasmcloud | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        - name: nats-leaf
          image: "{{ .Values.image.natsLeaf.repository }}:{{ .Values.image.natsLeaf.tag }}"
          imagePullPolicy: {{ .Values.image.natsLeaf.pullPolicy }}
          args:
            - -js
            - --config
            - /nats/nats.conf
          resources:
            {{- toYaml .Values.resources.natsLeaf | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: {{ include "wasmcloud-host.nats-config-name" . }}
              mountPath: /nats/nats.conf
              subPath: "nats.conf"
              readOnly: true
          {{- if .Values.config.natsCredentialsSecret }}
            - name: {{ .Values.config.natsCredentialsSecret }}
              mountPath: /nats/nats.creds
              subPath: "nats.creds"
              readOnly: true
          {{- end }}
      volumes:
        - name: {{ include "wasmcloud-host.nats-config-name" . }}
          configMap:
            name: {{ include "wasmcloud-host.nats-config-name" . }}
      {{- if .Values.config.natsCredentialsSecret }}
        - name: {{ .Values.config.natsCredentialsSecret }}
          secret: /nats/nats.creds
            secretName: {{ .Values.config.natsCredentialsSecret }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}