name = "Blobstore S3"
language = "rust"
version = "0.12.1"
type = "provider"
wit = "../../../crates/provider-blobstore-s3/wit"

[rust]
target_dir = "../../../"

[provider]
bin_name = "blobstore-s3-provider"
vendor = "wasmCloud"

[[registry.pull.sources]]
target = "wrpc:blobstore"
source = "https://github.com/wrpc/blobstore/archive/refs/tags/v0.2.0.tar.gz"

[[registry.pull.sources]]
target = "wrpc:extension"
source = "file://../../../wit/extension/wit"
